apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  namespace: default  # 원하는 namespace로 변경 가능
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath: # 클러스터 노드의 로컬 경로
    path: /mnt/data/mariadb-init   # 클러스터 노드의 디렉토리