name: Check .env is not committed

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check .env not committed
        run: |
          if git ls-files | grep -q ".env"; then
            echo ".env 파일이 Git에 포함되어 있습니다!"
            exit 1
          fi
