name: PR 시 CI 테스트 자동화

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write
      pull-requests: write

    env:
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_SERVICE_TEST }}

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Gradle 명령 실행 권한 부여
        run: chmod +x ./gradlew
        shell: bash

      - name: Redis 포트 열릴 때까지 대기
        run: |
          for i in {1..10}; do
            nc -z $REDIS_HOST $REDIS_PORT && echo "✅ Redis ready" && exit 0
            echo "⏳ Waiting for Redis..."
            sleep 2
          done
          echo "❌ Redis did not start in time" && exit 1

      - name: Gradle로 테스트 실행
        run: ./gradlew test

      - name: 테스트 결과를 PR 코멘트로 출력
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: 테스트 실패 시, 오류가 발생한 코드 라인에 코멘트 추가
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
